input_shape: [30, 30, 3]
num_classes: 43
epochs: 30
batch_size: 64
learning_rate: 0.001
optimizer: adam

models:
  baseline:
    conv_filters: [16, 32]
    batchnorm: false
    dropout: false

  improved:
    conv_filters: [32, 64, 128]
    batchnorm: false
    dropout: true
    dropout_rate: 0.3

  proposed:
    conv_filters: [16, 32, 64, 128]
    batchnorm: true
    dropout: true
    dropout_rate: 0.5
